yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = "posts"
urlpatterns = [
    path("", views.index, name='index'),
    path("group/<slug:slug>/", views.group_posts, name='group_list'),
    path("profile/<str:username>/", views.profile, name='profile'),
    path("posts/<int:post_id>/", views.post_detail, name='post_detail'),
    path(
        "create/", views.post_create, name='post_create'
    ),
    path("posts/<post_id>/edit/", views.post_edit, name='post_edit'),
    path(
        "posts/<int:post_id>/comment/",
        views.add_comment,
        name='add_comment'
    ),
    path("follow/", views.follow_index, name='follow_index'),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from .validators import validate_not_empty

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name="Название группы",
        help_text="Группа, к которой будет относиться пост",
    )
    slug = models.SlugField(
        max_length=100,
        unique=True,
        verbose_name="Слаг",
        help_text="Слаг, по которому можно найти группу",
    )
    description = models.TextField(
        verbose_name="Описание группы", help_text="Тематика группы"
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="posts",
        verbose_name="Группа",
        help_text="Группа, к которой будет относиться пост",
    )
    text = models.TextField(
        validators=[validate_not_empty],
        verbose_name="Текст поста",
        help_text="Текст поста",
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата публикации",
        help_text="Дата, когда был опубликован пост",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор поста",
        help_text="Автор поста",
    )
    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    class Meta:
        ordering = ("-pub_date",)
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        null=True,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Пост",
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор",
    )
    text = models.TextField(
        verbose_name="Текст комментария",
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата публикации"
    )

    class Meta:
        ordering = ("-created",)
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
    )

    class Meta:
        constraints = [models.UniqueConstraint(fields=('user', 'author'),
                       name="unique pair")]
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"

    def __str__(self):
        return f'{self.user} подписан на {self.author}'

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'image', 'text')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

from yatube.settings import PAGE_COUNT

from posts.models import Group, Post, User, Follow
from posts.forms import PostForm, CommentForm


from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

from yatube.settings import PAGE_COUNT

from .models import Group, Post, User


def index(request):
    template = "posts/index.html"
    posts = Post.objects.all()
    paginator = Paginator(posts, PAGE_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = "posts/group_list.html"
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, PAGE_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "group": group,
        "page_obj": page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = "posts/profile.html"
    post = get_object_or_404(User, username=username)
    posts = post.posts.all()
    paginator = Paginator(posts, PAGE_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user == post.following.all():
        following = True

    context = {
        "post": post,
        "page_obj": page_obj,
        "number_of_posts": posts.count(),
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = "posts/post_detail.html"
    post_detail = get_object_or_404(Post, pk=post_id)
    author = post_detail.author
    number_of_posts = author.posts.all().count()
    form = CommentForm(request.POST or None)
    comments = post_detail.comments.all()
    context = {
        "post_detail": post_detail,
        "number_of_posts": number_of_posts,
        "comments": comments,
        "form": form,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    if request.method != "POST":
        form = PostForm()
        return render(request, "posts/create.html", {"form": form})
    form = PostForm(request.POST, files=request.FILES or None)
    if not form.is_valid():
        return render(request, "posts/create.html", {"form": form})
    form.instance.author = request.user
    form.save()
    return redirect("posts:profile", request.user.username)


@login_required
def post_edit(request, post_id):
    post_edit = get_object_or_404(Post, pk=post_id)
    if request.method != "POST":
        form = PostForm(instance=post_edit)
        return render(
            request, "posts/create.html", {"form": form, "is_edit": post_edit}
        )
    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post_edit
    )
    if not form.is_valid():
        return render(request, "posts/create.html", {"form": form})
    form.save()
    return redirect("posts:post_detail", post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if not form.is_valid():
        return redirect("posts:post_detail", post_id)
    comment = form.save(commit=False)
    comment.author = request.user
    comment.post = post
    comment.save()
    return redirect("posts:post_detail", post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, PAGE_COUNT)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    post_author = get_object_or_404(User, username=username)
    follow = (Follow.objects.filter(user=request.user,
                                    author=post_author).count())
    if request.user != post_author and follow == 0:
        Follow.objects.create(user=request.user, author=post_author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    post_author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(user=request.user, author=post_author)
    if follower.exists():
        follower.delete()
    return redirect("posts:profile", username=username)

yatube/templates/posts/create.html
{% extends 'base.html' %}
{% load static %}
{% block static %}
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
{% endblock %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
          {% if is_edit %}
            Редактировать пост
          {% else %}       
            Новый пост
          {% endif %}             
          </div>
          <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

            <form method="post"
              {% if is_edit %}
                action="{% url 'posts:post_edit' is_edit.pk %}" enctype="multipart/form-data"
              {% else %}
                action="{% url 'posts:post_create' %}" enctype="multipart/form-data"
              {% endif %}
            >
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                {{ form.text.label }}                 
                <span class="required text-danger" >*</span>                 
              </label>
                  {{ form.text }}
              <small id="id_text-help" class="form-text text-muted">
                {{ form.text.help_text }}
              </small>                  
            </div>            
            <div class="form-group row my-3 p-3">
              <label for="id_group">
                {{ form.group.label }}                  
              </label>
              <select name="group" class="form-control" id="id_group">
                <option value={{ form.group }}</option>
              </select>
              <small id="id_group-help" class="form-text text-muted">
                {{ form.group.help_text }}
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_image">
                Картинка                      
              </label>
              {{ form.image }} 
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Добавить
                {% else %}
                  Сохранить
                {% endif %} 
              </button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block static %}
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
{% endblock %}
{% block title %}
  {{ page_obj.author.get_full_name }}
{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  <div class="container">
  <h1>{{ page_obj.author.get_full_name }}</h1>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaks }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
  </article>
  {% if post.group %}    
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}  
{% block static %}
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
{% endblock %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
  <article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text|linebreaks }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
  </article>
  {% if post.group %}    
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% load cache %}
{% load static %}
{% block static %}
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
{% endblock %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  <div class="container">
  <h1>Последние обновления на сайте</h1>
  {% cache 20 sidebar %}
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaks }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
  </article>
  {% if post.group %}    
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %}
</div>
{% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block static %}
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
{% endblock %}
{% block title %}
  {{ post_detail.text|slice:':31' }}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post_detail.pub_date|date:"d E Y" }} 
        </li>
          {% if post_detail.group %}   
          <li class="list-group-item">
            Группа: {{ post_detail.group }}
            <a href="{% url 'posts:group_list' post_detail.group.slug %}">
              все записи группы
            </a>
          {% endif %}
        </li>
        <li class="list-group-item">
          Автор: {{ post_detail.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ number_of_posts }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post_detail.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post_detail.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post_detail.text|linebreaks }}</p>
      {% if post_detail.author == request.user %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post_detail.pk %}">
        редактировать запись
      </a>
      {% endif %}  
    </article>
  </div>
{% include 'posts/includes/comments.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block static %}
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
{% endblock %}
{% block title %}
  {{ post.get_full_name }} Профайл пользователя
{% endblock %}
{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ post.get_full_name }}</h1>
    <h3>Всего постов: {{ number_of_posts }}</h3>
    {% if request.user.username == post.username %}
    {% else %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' post.username %}" role="button"
        >
        Отписаться
      </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' post.username %}" role="button"
        >
        Подписаться
        </a>
      {% endif %}
    {% endif %}
  </div>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
  <p>{{ post.text|linebreaks }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
  </article>
  {% if post.group %}    
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  </article>
{% endfor %} 
{% include 'posts/includes/paginator.html' %}
{% endblock %}